{"cells":[{"cell_type":"code","execution_count":null,"metadata":{"id":"MLVQvFa8JQKU"},"outputs":[],"source":["!apt-get update\n","!apt-get upgrade\n","!apt-get install make git zlib1g-dev libssl-dev gperf cmake g++"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"kV8nalIYiLDx"},"outputs":[],"source":["!git clone --recursive https://github.com/tdlib/telegram-bot-api.git\n","%cd telegram-bot-api"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"9PRKo2fDJwfz"},"outputs":[],"source":["!rm -rf build\n","!mkdir build\n","%cd build\n","!cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX:PATH=.. ..\n","!cmake --build . --target install\n","%cd ../..\n","!ls -l telegram-bot-api/bin/telegram-bot-api*"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":32,"status":"ok","timestamp":1704657900166,"user":{"displayName":"jjjaaa vaxy","userId":"06402702823282089972"},"user_tz":-330},"id":"E2SwrtCs9dq3","outputId":"881fc147-8b19-49eb-8517-73a9af3ad5ff"},"outputs":[{"name":"stdout","output_type":"stream","text":["/content\n"]}],"source":["%cd /content/"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"dMj-1_9BLzr1"},"outputs":[],"source":["#!git clone https://github.com/RtiM0/telegram-download-bot.git\n","!git clone https://github.com/dev-py-me/telegram-download-bot.git\n","%cd telegram-download-bot\n","!python -m pip install -r requirements.txt"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"y_Y7IHG1QWsb"},"outputs":[],"source":["!sudo mkdir /content/mega\n","!nohup rclone mount mega: /content/mega &"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"bghYSDBkT9EG"},"outputs":[],"source":["%cd /content/telegram-bot-api/bin/\n","!./telegram-bot-api --api-id 7712824 --api-hash 2d3673e18b462f8032c4eea2f50b9f52 --local"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"A2TEVUSFXHH5"},"outputs":[],"source":["%cd /content/telegram-download-bot/telegram-download-bot/\n","!python3 bot.py"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"QWu1zSpXUAm9"},"outputs":[],"source":["%cd /content/telegram-download-bot/\n","!python3 bot.py"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/"},"id":"Xh5LDyb1MDwe","outputId":"880d865a-1b11-4f73-b1b6-daa0c2a9a564"},"outputs":[{"name":"stdout","output_type":"stream","text":["/content/telegram-bot-api/bin\n","/content/telegram-download-bot\n","2024-01-07 20:05:57,269 - apscheduler.scheduler - INFO - Scheduler started\n","2024-01-07 20:05:57,270 - telegram.ext._application - INFO - Application started\n","{\"result\":{\"filecode\":\"a3uzmqh45g72\"},\"server_time\":\"2024-01-07 20:09:46\",\"msg\":\"OK\",\"status\":200}{\"msg\":\"OK\",\"result\":{\"filecode\":\"3bghbiczhnw0\"},\"server_time\":\"2024-01-07 20:10:20\",\"status\":200}{\"msg\":\"OK\",\"result\":{\"filecode\":\"m8iqqq86i0r5\"},\"status\":200,\"server_time\":\"2024-01-07 20:10:41\"}{\"server_time\":\"2024-01-07 20:11:12\",\"status\":200,\"msg\":\"OK\",\"result\":{\"filecode\":\"9v98936b3gzi\"}}{\"server_time\":\"2024-01-07 20:11:41\",\"msg\":\"OK\",\"result\":{\"filecode\":\"66xewlz975qe\"},\"status\":200}{\"server_time\":\"2024-01-07 20:12:19\",\"msg\":\"OK\",\"status\":200,\"result\":{\"filecode\":\"0er3jw3yy5p7\"}}{\"result\":{\"filecode\":\"v7ip5itm079f\"},\"server_time\":\"2024-01-07 20:12:57\",\"status\":200,\"msg\":\"OK\"}{\"status\":200,\"msg\":\"OK\",\"result\":{\"filecode\":\"ye4x22fxp1mo\"},\"server_time\":\"2024-01-07 20:13:28\"}{\"result\":{\"filecode\":\"ybwqn2s0p8zu\"},\"server_time\":\"2024-01-07 20:14:05\",\"msg\":\"OK\",\"status\":200}{\"result\":{\"filecode\":\"69z759h0hzzu\"},\"server_time\":\"2024-01-07 20:14:31\",\"msg\":\"OK\",\"status\":200}{\"result\":{\"filecode\":\"jjehky67k5is\"},\"server_time\":\"2024-01-07 20:15:11\",\"msg\":\"OK\",\"status\":200}{\"result\":{\"filecode\":\"ndcjiayt1ein\"},\"msg\":\"OK\",\"status\":200,\"server_time\":\"2024-01-07 20:15:44\"}{\"server_time\":\"2024-01-07 20:16:24\",\"result\":{\"filecode\":\"wqfnkrdr8yaz\"},\"status\":200,\"msg\":\"OK\"}{\"status\":200,\"server_time\":\"2024-01-07 20:17:05\",\"result\":{\"filecode\":\"7zff7e6zchi3\"},\"msg\":\"OK\"}{\"status\":200,\"server_time\":\"2024-01-07 20:17:25\",\"msg\":\"OK\",\"result\":{\"filecode\":\"0ar9gltj4ce3\"}}{\"msg\":\"OK\",\"result\":{\"filecode\":\"yrsy0yibpgqr\"},\"status\":200,\"server_time\":\"2024-01-07 20:17:52\"}{\"status\":200,\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:18:59\",\"result\":{\"filecode\":\"0cw6t8eolosq\"}}{\"result\":{\"filecode\":\"17di6hjtdqs4\"},\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:19:32\",\"status\":200}{\"result\":{\"filecode\":\"jtar8zp8coaf\"},\"status\":200,\"server_time\":\"2024-01-07 20:19:50\",\"msg\":\"OK\"}{\"server_time\":\"2024-01-07 20:20:32\",\"result\":{\"filecode\":\"lhit7ktq1bwu\"},\"status\":200,\"msg\":\"OK\"}{\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:21:02\",\"status\":200,\"result\":{\"filecode\":\"64q1ounr9x5v\"}}{\"status\":200,\"server_time\":\"2024-01-07 20:21:25\",\"msg\":\"OK\",\"result\":{\"filecode\":\"nuodxm7l9ra2\"}}{\"server_time\":\"2024-01-07 20:21:52\",\"result\":{\"filecode\":\"q553vlz39ap9\"},\"status\":200,\"msg\":\"OK\"}2024-01-07 20:22:13,168 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"server_time\":\"2024-01-07 20:22:59\",\"result\":{\"filecode\":\"slz6cf6ifiwa\"},\"msg\":\"OK\",\"status\":200}2024-01-07 20:23:25,167 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"msg\":\"OK\",\"status\":200,\"result\":{\"filecode\":\"gfj7un28ihi1\"},\"server_time\":\"2024-01-07 20:24:11\"}2024-01-07 20:24:30,556 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"status\":200,\"result\":{\"filecode\":\"hsvyq098gppr\"},\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:25:19\"}{\"status\":200,\"server_time\":\"2024-01-07 20:25:57\",\"result\":{\"filecode\":\"mtha5tgfnt2q\"},\"msg\":\"OK\"}{\"msg\":\"OK\",\"status\":200,\"server_time\":\"2024-01-07 20:26:24\",\"result\":{\"filecode\":\"13urooc67xcd\"}}{\"server_time\":\"2024-01-07 20:26:57\",\"status\":200,\"msg\":\"OK\",\"result\":{\"filecode\":\"8g14h2asuhf4\"}}{\"msg\":\"OK\",\"result\":{\"filecode\":\"gwpzaaczyt4d\"},\"status\":200,\"server_time\":\"2024-01-07 20:27:25\"}2024-01-07 20:27:40,169 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"server_time\":\"2024-01-07 20:28:03\",\"msg\":\"OK\",\"result\":{\"filecode\":\"d265ti8eglcj\"},\"status\":200}{\"server_time\":\"2024-01-07 20:28:27\",\"msg\":\"OK\",\"result\":{\"filecode\":\"l0bl79831smw\"},\"status\":200}2024-01-07 20:28:38,432 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"result\":{\"filecode\":\"ukovum05qa8i\"},\"status\":200,\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:29:17\"}2024-01-07 20:29:39,169 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","2024-01-07 20:29:51,961 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:30:32\",\"status\":200,\"result\":{\"filecode\":\"e6kwbljbo3e2\"}}{\"result\":{\"filecode\":\"71083e7zs1fe\"},\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:30:55\",\"status\":200}{\"result\":{\"filecode\":\"s2uvae1vagob\"},\"server_time\":\"2024-01-07 20:31:17\",\"msg\":\"OK\",\"status\":200}{\"server_time\":\"2024-01-07 20:31:59\",\"result\":{\"filecode\":\"xqa3ivrhjmuz\"},\"status\":200,\"msg\":\"OK\"}{\"msg\":\"OK\",\"result\":{\"filecode\":\"itw9ahhe7tv7\"},\"status\":200,\"server_time\":\"2024-01-07 20:32:34\"}{\"server_time\":\"2024-01-07 20:33:49\",\"status\":200,\"msg\":\"OK\",\"result\":{\"filecode\":\"t41f5q7sozdm\"}}{\"server_time\":\"2024-01-07 20:34:23\",\"result\":{\"filecode\":\"hbq0e7yix6uv\"},\"msg\":\"OK\",\"status\":200}{\"result\":{\"filecode\":\"pjvldol2rrce\"},\"status\":200,\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:34:41\"}{\"status\":200,\"server_time\":\"2024-01-07 20:35:09\",\"msg\":\"OK\",\"result\":{\"filecode\":\"l63j51ldk4o9\"}}{\"server_time\":\"2024-01-07 20:35:35\",\"msg\":\"OK\",\"status\":200,\"result\":{\"filecode\":\"p8sh5j7zhusl\"}}{\"result\":{\"filecode\":\"adn2j3oxtxck\"},\"status\":200,\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:36:18\"}{\"msg\":\"OK\",\"status\":200,\"result\":{\"filecode\":\"btymvpas8g3l\"},\"server_time\":\"2024-01-07 20:36:36\"}{\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:36:42\",\"status\":200,\"result\":{\"filecode\":\"k87njucyq468\"}}{\"status\":200,\"msg\":\"OK\",\"result\":{\"filecode\":\"zq837899muzx\"},\"server_time\":\"2024-01-07 20:37:17\"}{\"status\":200,\"server_time\":\"2024-01-07 20:37:55\",\"msg\":\"OK\",\"result\":{\"filecode\":\"08fnirn08g9f\"}}{\"status\":200,\"server_time\":\"2024-01-07 20:38:16\",\"msg\":\"OK\",\"result\":{\"filecode\":\"qyawp6807idn\"}}{\"result\":{\"filecode\":\"xsrl6bcg12li\"},\"msg\":\"OK\",\"status\":200,\"server_time\":\"2024-01-07 20:38:53\"}{\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:39:21\",\"status\":200,\"result\":{\"filecode\":\"r1w2jk2wwwap\"}}{\"result\":{\"filecode\":\"0o810jk9bbvh\"},\"msg\":\"OK\",\"status\":200,\"server_time\":\"2024-01-07 20:39:52\"}2024-01-07 20:40:12,301 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","2024-01-07 20:40:25,432 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"msg\":\"OK\",\"status\":200,\"result\":{\"filecode\":\"elnnsssplpq9\"},\"server_time\":\"2024-01-07 20:41:03\"}{\"result\":{\"filecode\":\"ewm34phz59tp\"},\"server_time\":\"2024-01-07 20:41:30\",\"msg\":\"OK\",\"status\":200}{\"status\":200,\"server_time\":\"2024-01-07 20:42:09\",\"msg\":\"OK\",\"result\":{\"filecode\":\"je1uge8tumc2\"}}{\"server_time\":\"2024-01-07 20:42:45\",\"msg\":\"OK\",\"result\":{\"filecode\":\"qvw572byqo78\"},\"status\":200}{\"status\":200,\"result\":{\"filecode\":\"au2wnjqush06\"},\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:43:28\"}{\"server_time\":\"2024-01-07 20:44:05\",\"msg\":\"OK\",\"result\":{\"filecode\":\"u2vbn9039agf\"},\"status\":200}{\"status\":200,\"result\":{\"filecode\":\"g6c2y7q5kqpy\"},\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:44:49\"}{\"status\":200,\"server_time\":\"2024-01-07 20:45:20\",\"msg\":\"OK\",\"result\":{\"filecode\":\"r871hcrn6bue\"}}{\"server_time\":\"2024-01-07 20:45:58\",\"status\":200,\"msg\":\"OK\",\"result\":{\"filecode\":\"9d01fkxb15rt\"}}{\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:46:32\",\"result\":{\"filecode\":\"7pduodrbvqz6\"},\"status\":200}{\"status\":200,\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:47:03\",\"result\":{\"filecode\":\"zxbfvotun2uu\"}}{\"server_time\":\"2024-01-07 20:47:44\",\"status\":200,\"result\":{\"filecode\":\"dj36pu501d6h\"},\"msg\":\"OK\"}{\"result\":{\"filecode\":\"q7fcotxp6tja\"},\"server_time\":\"2024-01-07 20:48:27\",\"status\":200,\"msg\":\"OK\"}{\"result\":{\"filecode\":\"w5jcpj2uzolo\"},\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:49:03\",\"status\":200}{\"server_time\":\"2024-01-07 20:49:35\",\"msg\":\"OK\",\"result\":{\"filecode\":\"fqayg5m6t3ds\"},\"status\":200}{\"result\":{\"filecode\":\"8sw9bacp57su\"},\"msg\":\"OK\",\"status\":200,\"server_time\":\"2024-01-07 20:50:12\"}{\"status\":200,\"server_time\":\"2024-01-07 20:51:00\",\"msg\":\"OK\",\"result\":{\"filecode\":\"it4yb7ruzfq8\"}}{\"status\":200,\"msg\":\"OK\",\"result\":{\"filecode\":\"2i6b2e1mkl4i\"},\"server_time\":\"2024-01-07 20:51:30\"}{\"server_time\":\"2024-01-07 20:52:02\",\"msg\":\"OK\",\"status\":200,\"result\":{\"filecode\":\"swxgeintdhie\"}}{\"msg\":\"OK\",\"result\":{\"filecode\":\"mim8s969rcoj\"},\"server_time\":\"2024-01-07 20:52:38\",\"status\":200}{\"msg\":\"OK\",\"status\":200,\"result\":{\"filecode\":\"b6as70oiilt7\"},\"server_time\":\"2024-01-07 20:53:01\"}{\"server_time\":\"2024-01-07 20:53:44\",\"status\":200,\"msg\":\"OK\",\"result\":{\"filecode\":\"hvi2ilp7s39f\"}}{\"server_time\":\"2024-01-07 20:54:09\",\"result\":{\"filecode\":\"rjr59t8xfl5x\"},\"msg\":\"OK\",\"status\":200}{\"msg\":\"OK\",\"status\":200,\"result\":{\"filecode\":\"87j0zybamo9w\"},\"server_time\":\"2024-01-07 20:54:45\"}{\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:55:29\",\"result\":{\"filecode\":\"8mh0atcznttw\"},\"status\":200}{\"status\":200,\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:56:05\",\"result\":{\"filecode\":\"h92vs392sh5y\"}}{\"server_time\":\"2024-01-07 20:56:44\",\"msg\":\"OK\",\"status\":200,\"result\":{\"filecode\":\"32s8fkbo6c0f\"}}{\"server_time\":\"2024-01-07 20:57:16\",\"result\":{\"filecode\":\"rxh174py4e5n\"},\"msg\":\"OK\",\"status\":200}{\"status\":200,\"server_time\":\"2024-01-07 20:57:52\",\"result\":{\"filecode\":\"eqcldhrwgn0w\"},\"msg\":\"OK\"}{\"msg\":\"OK\",\"server_time\":\"2024-01-07 20:58:21\",\"result\":{\"filecode\":\"92qrnml6mx4y\"},\"status\":200}{\"server_time\":\"2024-01-07 20:59:05\",\"status\":200,\"msg\":\"OK\",\"result\":{\"filecode\":\"4g74w19o28rw\"}}{\"server_time\":\"2024-01-07 20:59:41\",\"msg\":\"OK\",\"status\":200,\"result\":{\"filecode\":\"n38n74hmf632\"}}{\"server_time\":\"2024-01-07 21:00:06\",\"status\":200,\"msg\":\"OK\",\"result\":{\"filecode\":\"rewtl87texmj\"}}{\"status\":200,\"server_time\":\"2024-01-07 21:00:37\",\"result\":{\"filecode\":\"qfo72z2yd5sq\"},\"msg\":\"OK\"}{\"result\":{\"filecode\":\"vvgxrqh999a3\"},\"server_time\":\"2024-01-07 21:01:13\",\"msg\":\"OK\",\"status\":200}{\"result\":{\"filecode\":\"r7h8qp2up8vf\"},\"status\":200,\"msg\":\"OK\",\"server_time\":\"2024-01-07 21:01:51\"}{\"server_time\":\"2024-01-07 21:02:15\",\"msg\":\"OK\",\"result\":{\"filecode\":\"fg88hkoy6r1c\"},\"status\":200}{\"server_time\":\"2024-01-07 21:02:36\",\"result\":{\"filecode\":\"m86bimerc3j6\"},\"msg\":\"OK\",\"status\":200}2024-01-07 21:02:51,657 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"result\":{\"filecode\":\"bhft1lxfxyxe\"},\"status\":200,\"server_time\":\"2024-01-07 21:03:25\",\"msg\":\"OK\"}2024-01-07 21:03:49,166 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"status\":200,\"server_time\":\"2024-01-07 21:04:39\",\"result\":{\"filecode\":\"28ta1zilulgf\"},\"msg\":\"OK\"}2024-01-07 21:05:02,433 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"result\":{\"filecode\":\"psswwgho267x\"},\"msg\":\"OK\",\"status\":200,\"server_time\":\"2024-01-07 21:05:40\"}{\"result\":{\"filecode\":\"4ds4s6zcvj83\"},\"server_time\":\"2024-01-07 21:06:45\",\"status\":200,\"msg\":\"OK\"}{\"server_time\":\"2024-01-07 21:07:16\",\"msg\":\"OK\",\"status\":200,\"result\":{\"filecode\":\"wlg1jzjinim9\"}}{\"msg\":\"OK\",\"result\":{\"filecode\":\"aqjcvl1ww8l1\"},\"server_time\":\"2024-01-07 21:07:45\",\"status\":200}{\"result\":{\"filecode\":\"6yl541ncruby\"},\"server_time\":\"2024-01-07 21:08:24\",\"status\":200,\"msg\":\"OK\"}{\"status\":200,\"server_time\":\"2024-01-07 21:08:52\",\"msg\":\"OK\",\"result\":{\"filecode\":\"q9ew98pwhzz6\"}}{\"status\":200,\"result\":{\"filecode\":\"h2u1z5z63nlq\"},\"msg\":\"OK\",\"server_time\":\"2024-01-07 21:09:37\"}{\"status\":200,\"result\":{\"filecode\":\"du7ppwx86ddj\"},\"msg\":\"OK\",\"server_time\":\"2024-01-07 21:10:09\"}{\"msg\":\"OK\",\"status\":200,\"server_time\":\"2024-01-07 21:10:54\",\"result\":{\"filecode\":\"po7aa6cpf69z\"}}{\"server_time\":\"2024-01-07 21:11:30\",\"result\":{\"filecode\":\"ui8117cqk5jr\"},\"status\":200,\"msg\":\"OK\"}{\"result\":{\"filecode\":\"pj6cgtnaikzp\"},\"server_time\":\"2024-01-07 21:12:02\",\"status\":200,\"msg\":\"OK\"}{\"msg\":\"OK\",\"server_time\":\"2024-01-07 21:12:44\",\"status\":200,\"result\":{\"filecode\":\"kmyknrvk297e\"}}{\"msg\":\"OK\",\"result\":{\"filecode\":\"h9y3689roxub\"},\"status\":200,\"server_time\":\"2024-01-07 21:13:25\"}{\"result\":{\"filecode\":\"fyjqrq0twwcb\"},\"status\":200,\"msg\":\"OK\",\"server_time\":\"2024-01-07 21:13:57\"}{\"server_time\":\"2024-01-07 21:14:33\",\"result\":{\"filecode\":\"bewaqj1yi33g\"},\"status\":200,\"msg\":\"OK\"}{\"server_time\":\"2024-01-07 21:14:49\",\"status\":200,\"msg\":\"OK\",\"result\":{\"filecode\":\"il6wp2it0d4t\"}}{\"status\":200,\"server_time\":\"2024-01-07 21:15:19\",\"msg\":\"OK\",\"result\":{\"filecode\":\"bepym69kq7rk\"}}{\"msg\":\"OK\",\"status\":200,\"server_time\":\"2024-01-07 21:15:55\",\"result\":{\"filecode\":\"3acf3h2ojkwk\"}}------- Stack Backtrace -------\n","./telegram-bot-api(+0x20cef7b)[0x5d24d62d0f7b]\n","./telegram-bot-api(+0x20cf475)[0x5d24d62d1475]\n","./telegram-bot-api(+0x16f503)[0x5d24d4371503]\n","/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x78033addf520]\n","/lib/x86_64-linux-gnu/libc.so.6(epoll_wait+0x5e)[0x78033aec2c3e]\n","./telegram-bot-api(+0x20d4317)[0x5d24d62d6317]\n","./telegram-bot-api(+0x3c8e79)[0x5d24d45cae79]\n","./telegram-bot-api(+0x3c96f6)[0x5d24d45cb6f6]\n","./telegram-bot-api(+0x3bc986)[0x5d24d45be986]\n","./telegram-bot-api(+0x3bcfd0)[0x5d24d45befd0]\n","./telegram-bot-api(+0x3c004d)[0x5d24d45c204d]\n","./telegram-bot-api(+0x3bf2fb)[0x5d24d45c12fb]\n","./telegram-bot-api(+0x3be1db)[0x5d24d45c01db]\n","./telegram-bot-api(+0x3be202)[0x5d24d45c0202]\n","./telegram-bot-api(+0x3be226)[0x5d24d45c0226]\n","./telegram-bot-api(+0x3c114c)[0x5d24d45c314c]\n","./telegram-bot-api(+0x3c1178)[0x5d24d45c3178]\n","./telegram-bot-api(+0x3be84d)[0x5d24d45c084d]\n","./telegram-bot-api(+0x3bd86b)[0x5d24d45bf86b]\n","./telegram-bot-api(+0x3bca3f)[0x5d24d45bea3f]\n","/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3)[0x78033ae31ac3]\n","/lib/x86_64-linux-gnu/libc.so.6(+0x126660)[0x78033aec3660]\n","-------------------------------\n","------- Stack Backtrace -------\n","./telegram-bot-api(+0x20cef7b)[0x5d24d62d0f7b]\n","./telegram-bot-api(+0x20cf475)[0x5d24d62d1475]\n","./telegram-bot-api(+0x16f503)[0x5d24d4371503]\n","/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x78033addf520]\n","/lib/x86_64-linux-gnu/libc.so.6(epoll_wait+0x5e)[0x78033aec2c3e]\n","./telegram-bot-api(+0x20d4317)[0x5d24d62d6317]\n","./telegram-bot-api(+0x3c8e79)[0x5d24d45cae79]\n","./telegram-bot-api(+0x3c96f6)[0x5d24d45cb6f6]\n","./telegram-bot-api(+0x3bc986)[0x5d24d45be986]\n","./telegram-bot-api(+0x3bd1d9)[0x5d24d45bf1d9]\n","./telegram-bot-api(+0x16ed2a)[0x5d24d4370d2a]\n","./telegram-bot-api(+0x174009)[0x5d24d4376009]\n","./telegram-bot-api(+0x174b51)[0x5d24d4376b51]\n","/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x78033adc6d90]\n","/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x78033adc6e40]\n","./telegram-bot-api(+0x168235)[0x5d24d436a235]\n","-------------------------------\n","{\"server_time\":\"2024-01-07 21:16:18\",\"result\":{\"filecode\":\"n4veoso2hgyz\"},\"status\":200,\"msg\":\"OK\"}{\"result\":{\"filecode\":\"s9qlg5ojovi2\"},\"server_time\":\"2024-01-07 21:16:48\",\"msg\":\"OK\",\"status\":200}{\"server_time\":\"2024-01-07 21:17:24\",\"status\":200,\"msg\":\"OK\",\"result\":{\"filecode\":\"huqlqq1h08gy\"}}{\"msg\":\"OK\",\"server_time\":\"2024-01-07 21:17:57\",\"status\":200,\"result\":{\"filecode\":\"z8klzk52my2i\"}}{\"result\":{\"filecode\":\"nii2tchqwc1s\"},\"msg\":\"OK\",\"status\":200,\"server_time\":\"2024-01-07 21:18:17\"}{\"server_time\":\"2024-01-07 21:18:48\",\"result\":{\"filecode\":\"4j76wpqywczc\"},\"status\":200,\"msg\":\"OK\"}{\"result\":{\"filecode\":\"7taqwairaw97\"},\"status\":200,\"msg\":\"OK\",\"server_time\":\"2024-01-07 21:19:22\"}{\"msg\":\"OK\",\"result\":{\"filecode\":\"ik3y0a1obqx1\"},\"status\":200,\"server_time\":\"2024-01-07 21:19:56\"}{\"result\":{\"filecode\":\"59qzohu6n8qg\"},\"server_time\":\"2024-01-07 21:20:23\",\"status\":200,\"msg\":\"OK\"}{\"result\":{\"filecode\":\"9n2k4vixjkok\"},\"msg\":\"OK\",\"status\":200,\"server_time\":\"2024-01-07 21:20:57\"}{\"server_time\":\"2024-01-07 21:21:29\",\"status\":200,\"msg\":\"OK\",\"result\":{\"filecode\":\"3t4h3qzeo61w\"}}{\"status\":200,\"server_time\":\"2024-01-07 21:22:03\",\"result\":{\"filecode\":\"8ar7f5ooco8x\"},\"msg\":\"OK\"}{\"msg\":\"OK\",\"status\":200,\"result\":{\"filecode\":\"tr7qfcr8lkbc\"},\"server_time\":\"2024-01-07 21:22:41\"}{\"result\":{\"filecode\":\"92faluqhqbfy\"},\"msg\":\"OK\",\"server_time\":\"2024-01-07 21:23:06\",\"status\":200}{\"status\":200,\"msg\":\"OK\",\"result\":{\"filecode\":\"wprpd2ud2ifk\"},\"server_time\":\"2024-01-07 21:23:38\"}2024-01-07 21:23:59,683 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"result\":{\"filecode\":\"aownmlldha60\"},\"server_time\":\"2024-01-07 21:24:56\",\"msg\":\"OK\",\"status\":200}2024-01-07 21:25:17,167 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"msg\":\"OK\",\"status\":200,\"server_time\":\"2024-01-07 21:25:56\",\"result\":{\"filecode\":\"fwniw735je18\"}}2024-01-07 21:26:20,167 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"status\":200,\"server_time\":\"2024-01-07 21:26:44\",\"msg\":\"OK\",\"result\":{\"filecode\":\"uxyg7p6ys3w8\"}}{\"server_time\":\"2024-01-07 21:27:01\",\"result\":{\"filecode\":\"k39hcgkltama\"},\"status\":200,\"msg\":\"OK\"}{\"server_time\":\"2024-01-07 21:27:15\",\"status\":200,\"result\":{\"filecode\":\"llz0k012fiyu\"},\"msg\":\"OK\"}2024-01-07 21:27:25,936 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"result\":{\"filecode\":\"bdf8i5zpblog\"},\"server_time\":\"2024-01-07 21:27:44\",\"status\":200,\"msg\":\"OK\"}{\"msg\":\"OK\",\"result\":{\"filecode\":\"jr1gyexk1g1w\"},\"status\":200,\"server_time\":\"2024-01-07 21:28:38\"}{\"result\":{\"filecode\":\"ph8xr9xmx5oh\"},\"msg\":\"OK\",\"server_time\":\"2024-01-07 21:29:15\",\"status\":200}{\"msg\":\"OK\",\"result\":{\"filecode\":\"1s66hgvi6iu3\"},\"status\":200,\"server_time\":\"2024-01-07 21:29:39\"}{\"server_time\":\"2024-01-07 21:29:58\",\"status\":200,\"result\":{\"filecode\":\"87vhwohnt4lw\"},\"msg\":\"OK\"}{\"status\":200,\"result\":{\"filecode\":\"69idn4ep0hnn\"},\"server_time\":\"2024-01-07 21:30:24\",\"msg\":\"OK\"}2024-01-07 21:30:37,167 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"result\":{\"filecode\":\"4lgpjbhugw7a\"},\"status\":200,\"msg\":\"OK\",\"server_time\":\"2024-01-07 21:31:07\"}2024-01-07 21:31:36,167 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py\", line 983, in process_update\n","    await coroutine\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/ext/_handler.py\", line 137, in handle_update\n","    return await self.callback(update, context)\n","  File \"/content/telegram-download-bot/bot.py\", line 76, in video\n","    file = await context.bot.get_file(document)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 236, in decorator\n","    result = await func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 2978, in get_file\n","    result = await self._post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/_bot.py\", line 309, in _post\n","    return await request.post(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 162, in post\n","    result = await self._request_wrapper(\n","  File \"/usr/local/lib/python3.10/dist-packages/telegram/request/_baserequest.py\", line 325, in _request_wrapper\n","    raise BadRequest(message)\n","telegram.error.BadRequest: Wrong file_id or the file is temporarily unavailable\n","{\"status\":200,\"msg\":\"OK\",\"server_time\":\"2024-01-07 21:32:18\",\"result\":{\"filecode\":\"5pdd8lzdn47h\"}}{\"server_time\":\"2024-01-07 21:32:54\",\"msg\":\"OK\",\"status\":200,\"result\":{\"filecode\":\"y2otu2pg48sz\"}}{\"msg\":\"OK\",\"status\":200,\"result\":{\"filecode\":\"1x7gp3sffqdx\"},\"server_time\":\"2024-01-07 21:33:38\"}{\"server_time\":\"2024-01-07 21:34:16\",\"msg\":\"OK\",\"status\":200,\"result\":{\"filecode\":\"a4nkt900ewbn\"}}{\"server_time\":\"2024-01-07 21:34:55\",\"result\":{\"filecode\":\"ncel85ss9fax\"},\"msg\":\"OK\",\"status\":200}{\"result\":{\"filecode\":\"lzdvtvmdvs6e\"},\"server_time\":\"2024-01-07 21:35:42\",\"msg\":\"OK\",\"status\":200}"]}],"source":["import os\n","import threading\n","\n","def conda():\n","  %cd /content/telegram-bot-api/bin/\n","  !./telegram-bot-api --api-id 7712824 --api-hash 2d3673e18b462f8032c4eea2f50b9f52 --local\n","\n","def wget():\n","  %cd /content/telegram-download-bot/\n","  !python3 bot.py\n","\n","# creating thread\n","t1 = threading.Thread(target=conda, args=())\n","t2 = threading.Thread(target=wget, args=())\n","\n","# starting thread 1\n","t1.start()\n","# starting thread 2\n","t2.start()\n","# startling thread\n","\n","# wait until thread 1 is completely executed\n","t1.join()\n","# wait until thread 2 is completely executed\n","t2.join()\n","# wait until thread 2 is completely executed\n","\n","\n","# both threads completely executed\n","print(\"Done!\")"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"S3EhvQHp3iD8"},"outputs":[],"source":["!rm -rf /content/mega/*.MP4"]}],"metadata":{"colab":{"provenance":[],"mount_file_id":"1t_C1LcqaHhWlnDDOUFMqtXgpH5BS5vbI","authorship_tag":"ABX9TyPt4zyed4w+qJSBPfaU2+3I"},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}